spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlin_lessons?useTimezone=true&serverTimezone=UTC
    username: root
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false